"""Configurable PDF letter format metadata."""

PDF_SETTINGS = {
    "title": "University Result Correction Letter",
    "issuer": "Controller of Examinations",
    "signature_label": "Authorized Signatory",
    "footer": "Auto-generated by RLE/RPV system",
}
